# Generated by Django 4.2.6 on 2023-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
